Update install script

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -77,6 +77,8 @@ install_elm() {
       tar zxf "$source_path" -C "$distination_path" --strip-components=1 || fail "Could not uncompress"
     fi
 
+    chmod +x "${install_path}/bin/elm*" || fail "Could not find uncompressed binary"
+
     echo "The installation was successful!"
   ) || (
     rm -rf "$install_path"
